# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0
# Adapted from: https://github.com/bitnami/containers/blob/43aeee3153936450ce4859ed08b135c91113d80d/bitnami/wordpress/docker-compose.yml

services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    networks:
      - wordpress-network
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    env_file:
      - ./.env
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
  wordpress:
    image: docker.io/bitnami/wordpress-nginx:latest
    networks:
      - wordpress-network
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
    depends_on:
      - mariadb
    links:
      - mariadb
    env_file:
      - ./.env
    environment:
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - WORDPRESS_ENABLE_HTTPS=yes
      - WORDPRESS_BLOG_NAME="Hui Ling Wong"

networks:
  wordpress-network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local